#!/usr/bin/env bash
#
# Production-ready pyenv installation script for any Debian-based system
# • Installs all build dependencies first (with apt-get update)
# • Clones/builds pyenv to /opt/pyenv exactly for system-wide availability
# • Installs pyenv-update plugin
# • Creates secure root-only wrappers: pyenv-install, pyenv-uninstall, pyenv-update
# • Fully idempotent (safe to re-run)
# • Strict error handling, clear status messages, and root check
# • Creates /etc/profile.d/pyenv.sh for system-wide availability
# • Creates secure root-only wrappers in /usr/local/bin for install/uninstall
# • Hardened with --no-install-recommends, shallow clone, safe git updates, and permission lockdown
#
# Usage:
#   sudo ./install-pyenv.sh
#   (After running, restart your shell or run: source /etc/profile)

set -euo pipefail

# Colors for clear terminal output
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

echo_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

echo_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

# Must be run as root
if [[ "${EUID}" -ne 0 ]]; then
    echo_error "This script must be run as root (use sudo)."
    exit 1
fi

PYENV_ROOT="/opt/pyenv"
PROFILE_D="/etc/profile.d/pyenv.sh"
INSTALL_WRAPPER="/usr/local/bin/pyenv-install"
UNINSTALL_WRAPPER="/usr/local/bin/pyenv-uninstall"
UPDATE_WRAPPER="/usr/local/bin/pyenv-update"

echo_status "=== Starting production pyenv installation ==="

# 1. Update package index (required on fresh installs)
echo_status "Updating apt package index..."
apt-get update -qq

# 2. Install all required build packages
echo_status "Installing build dependencies (make, Python build libs, git, etc.)..."
apt-get install -y --no-install-recommends \
    make \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    curl \
    git \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libffi-dev \
    liblzma-dev \
    libzstd-dev

# 3. Prepare /opt/pyenv directory (idempotent + safety check)
echo_status "Preparing installation directory at ${PYENV_ROOT}..."
mkdir -p "${PYENV_ROOT}"

if [[ -d "${PYENV_ROOT}/.git" ]]; then
    echo_status "pyenv repository already exists. Performing safe fast-forward update..."
    (
        cd "${PYENV_ROOT}"
        git pull --ff-only --quiet || echo_status "pyenv already up-to-date (no fast-forward update needed)."
    )
else
    # Safety: if directory exists but is not a git repo and is not empty → fail loudly
    if [[ -d "${PYENV_ROOT}" && "$(ls -A "${PYENV_ROOT}" 2>/dev/null)" ]]; then
        echo_error "Directory ${PYENV_ROOT} exists, is not empty, and is not a pyenv git repository."
        echo_error "Please remove it manually if you want a clean reinstall: rm -rf ${PYENV_ROOT}"
        exit 1
    fi

    echo_status "Cloning pyenv (shallow clone for efficiency)..."
    git clone --depth 1 https://github.com/pyenv/pyenv.git "${PYENV_ROOT}"
fi

# 4. Install pyenv-update plugin
PLUGIN_DIR="${PYENV_ROOT}/plugins/pyenv-update"
echo_status "Installing/updating pyenv-update plugin..."
if [[ -d "${PLUGIN_DIR}/.git" ]]; then
    echo_status "pyenv-update plugin already exists. Updating..."
    (
        cd "${PLUGIN_DIR}"
        git pull --ff-only --quiet || echo_status "pyenv-update already up-to-date."
    )
else
    git clone --depth 1 https://github.com/pyenv/pyenv-update.git "${PLUGIN_DIR}"
fi

# 5. Build pyenv
echo_status "Building pyenv..."
(
    cd "${PYENV_ROOT}"
    echo_status "→ Running src/configure && make -C src ..."
    src/configure && make -C src
)

# 6. Create system-wide environment file so pyenv is available to all users
echo_status "Creating system-wide pyenv configuration (${PROFILE_D})..."
cat > "${PROFILE_D}" << EOF
# System-wide pyenv configuration (installed by production script)
# Do NOT edit this file directly — it will be overwritten on re-install.

export PYENV_ROOT="${PYENV_ROOT}"
export PATH="\${PYENV_ROOT}/bin:\${PATH}"

# Initialize pyenv for login shells (PATH)
eval "\$(pyenv init --path --no-rehash)"

# For interactive shells (bash or zsh) — enables pyenv command completion, virtualenv hooks, etc.
if [[ -n "\${BASH_VERSION:-}" || -n "\${ZSH_VERSION:-}" ]]; then
    eval "\$(pyenv init --no-rehash -)"
fi
EOF

chmod 644 "${PROFILE_D}"

# 7. Create secure optimized wrapper for pyenv install
echo_status "Creating secure optimized install wrapper (${INSTALL_WRAPPER})..."
cat > "${INSTALL_WRAPPER}" << EOF
#!/usr/bin/env bash
#
# Secure wrapper: always builds Python with production optimizations
# Hardcoded variables — never trusts user environment (security best practice)

RED='\033[0;31m'
NC='\033[0m'

echo_error() {
    echo -e "\${RED}[ERROR]\${NC} \$1" >&2
}

# Must be run as root
if [[ "\${EUID}" -ne 0 ]]; then
    echo_error "This script must be run as root (use sudo)."
    exit 1
fi

export PYENV_ROOT="${PYENV_ROOT}"
export PYTHON_CONFIGURE_OPTS="--enable-optimizations --with-lto"
export PYTHON_CFLAGS="-march=native -mtune=native"
export MAKE_OPTS="-j\$(nproc)"

exec "\${PYENV_ROOT}/bin/pyenv" install "\$@"
EOF

# 8. Create secure uninstall wrapper
echo_status "Creating secure uninstall wrapper (${UNINSTALL_WRAPPER})..."
cat > "${UNINSTALL_WRAPPER}" << EOF
#!/usr/bin/env bash
#
# Secure wrapper for pyenv uninstall (root-only for safety)

RED='\033[0;31m'
NC='\033[0m'

echo_error() {
    echo -e "\${RED}[ERROR]\${NC} \$1" >&2
}

# Must be run as root
if [[ "\${EUID}" -ne 0 ]]; then
    echo_error "This script must be run as root (use sudo)."
    exit 1
fi

export PYENV_ROOT="${PYENV_ROOT}"

exec "\${PYENV_ROOT}/bin/pyenv" uninstall "\$@"
EOF

# 9. Create secure update wrapper
echo_status "Creating secure update wrapper (${UPDATE_WRAPPER})..."
cat > "${UPDATE_WRAPPER}" << EOF
#!/usr/bin/env bash
#
# Secure wrapper for pyenv update (updates pyenv + all plugins)

RED='\033[0;31m'
NC='\033[0m'

echo_error() {
    echo -e "\${RED}[ERROR]\${NC} \$1" >&2
}

# Must be run as root
if [[ "\${EUID}" -ne 0 ]]; then
    echo_error "This script must be run as root (use sudo)."
    exit 1
fi

export PYENV_ROOT="${PYENV_ROOT}"

exec "\${PYENV_ROOT}/bin/pyenv" update "\$@"
EOF

# 10. Lock down permissions
echo_status "Locking down permissions for production security..."
chown -R root:root "${PYENV_ROOT}"
chmod -R 755 "${PYENV_ROOT}"
chown root:root "${INSTALL_WRAPPER}" "${UNINSTALL_WRAPPER}" "${UPDATE_WRAPPER}"
chmod 755 "${INSTALL_WRAPPER}" "${UNINSTALL_WRAPPER}" "${UPDATE_WRAPPER}"

echo_status "✅ pyenv installation completed successfully!"
echo_status "   • Installed at:                ${PYENV_ROOT}"
echo_status "   • pyenv-update plugin:         ${PLUGIN_DIR}"
echo_status "   • Environment file:            ${PROFILE_D}"
echo_status "   • Optimized install wrapper:   ${INSTALL_WRAPPER}"
echo_status "   • Secure uninstall wrapper:    ${UNINSTALL_WRAPPER}"
echo_status "   • Secure update wrapper:       ${UPDATE_WRAPPER}"

echo ""
echo_status "Next steps:"
echo "   1. Restart your shell or run:   source /etc/profile"
echo "   2. Verify:                      pyenv --version"
echo "   3. Install optimized Python:    sudo pyenv-install 3.12.10    (or any version)"
echo "   4. Uninstall a version:         sudo pyenv-uninstall 3.12.10  (or any version)"
echo "   5. Update pyenv:                sudo pyenv-update"
echo ""
echo_status "Script is fully idempotent — re-run anytime for updates or repairs."